# Generated by Django 5.1.4 on 2024-12-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='author',
            new_name='author_p',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='author_q',
        ),
    ]
