# Generated by Django 5.1.4 on 2024-12-28 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='author_p',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='author_q',
            field=models.ForeignKey(default='author', on_delete=django.db.models.deletion.CASCADE, related_name='author_q', to=settings.AUTH_USER_MODEL),
        ),
    ]
