# Generated by Django 5.1.4 on 2024-12-18 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_question_answer_text_pack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pack',
            new_name='Packs',
        ),
    ]
